In [77]:
import pandas as pd

df = pd.read_csv("data/raw.csv")

print("Shape:", df.shape)
df.head()

Shape: (10194, 18)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [78]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  object
 7   City            10194 non-null  object
 8   State/Province  10194 non-null  object
 9   Postal Code     10194 non-null  object
 10  Division        10194 non-null  object
 11  Region          10194 non-null  object
 12  Product ID      10194 non-null  object
 13  Product Name    10194 non-null  object
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: float64(3), int64(3), object(12)
memory usage: 1.4+ MB
None

In [79]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Division          0
Region            0
Product ID        0
Product Name      0
Sales             0
Units             0
Gross Profit      0
Cost              0
dtype: int64

In [80]:
df["Order Date"] = pd.to_datetime(df["Order Date"], dayfirst=True)
df["Ship Date"] = pd.to_datetime(df["Ship Date"], dayfirst=True)

df[["Order Date", "Ship Date"]].dtypes

Order Date    datetime64[ns]
Ship Date     datetime64[ns]
dtype: object

In [81]:
df["Order Date"] = pd.to_datetime(df["Order Date"], format="mixed")
df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="mixed")

df["Lead Time"] = (df["Ship Date"] - df["Order Date"]).dt.days

df["Lead Time"].describe()

count    10194.000000
mean      1320.841868
std        262.444892
min        904.000000
25%       1271.000000
50%       1274.000000
75%       1638.000000
max       1642.000000
Name: Lead Time, dtype: float64

In [82]:
df[["Order Date", "Ship Date"]].head(10)

  Order Date  Ship Date
0 2024-01-03 2026-06-30
1 2024-01-04 2026-07-01
2 2024-01-04 2026-07-01
3 2024-01-04 2026-07-01
4 2024-01-05 2026-07-05
5 2024-01-06 2026-07-03
6 2024-01-06 2026-07-03
7 2024-01-06 2026-06-30
8 2024-01-06 2026-07-03
9 2024-01-06 2026-07-03

In [83]:
print("Order Date range:")
print(df["Order Date"].min(), "to", df["Order Date"].max())

print("\nShip Date range:")
print(df["Ship Date"].min(), "to", df["Ship Date"].max())

Order Date range:
2024-01-02 00:00:00 to 2025-12-31 00:00:00

Ship Date range:
2026-06-30 00:00:00 to 2030-06-28 00:00:00

In [84]:
df["Lead Time Months"] = (
    (df["Ship Date"] - df["Order Date"]).dt.days / 30
).round(1)

df["Lead Time Months"].describe()

count    10194.000000
mean        44.028085
std          8.746072
min         30.100000
25%         42.400000
50%         42.500000
75%         54.600000
max         54.700000
Name: Lead Time Months, dtype: float64

In [85]:
product_factory_map = {
    "Wonka Bar - Nutty Crunch Surprise": "Lot's O' Nuts",
    "Wonka Bar - Fudge Mallows": "Lot's O' Nuts",
    "Wonka Bar -Scrumdiddlyumptious": "Lot's O' Nuts",
    "Wonka Bar - Milk Chocolate": "Wicked Choccy's",
    "Wonka Bar - Triple Dazzle Caramel": "Wicked Choccy's",
    "Laffy Taffy": "Sugar Shack",
    "SweeTARTS": "Sugar Shack",
    "Nerds": "Sugar Shack",
    "Fun Dip": "Sugar Shack",
    "Fizzy Lifting Drinks": "Sugar Shack",
    "Everlasting Gobstopper": "Secret Factory",
    "Hair Toffee": "The Other Factory",
    "Lickable Wallpaper": "Secret Factory",
    "Wonka Gum": "Secret Factory",
    "Kazookles": "The Other Factory"
}

In [86]:
df["Factory"] = df["Product Name"].map(product_factory_map)

df[["Product Name", "Factory"]].head()

                        Product Name          Factory
0         Wonka Bar - Milk Chocolate  Wicked Choccy's
1  Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's
2  Wonka Bar - Nutty Crunch Surprise    Lot's O' Nuts
3     Wonka Bar -Scrumdiddlyumptious    Lot's O' Nuts
4  Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's

In [87]:
df["Factory"].isnull().sum()

np.int64(0)

In [88]:
factory_coords = {
    "Lot's O' Nuts": (32.881893, -111.768036),
    "Wicked Choccy's": (32.076176, -81.088371),
    "Sugar Shack": (48.11914, -96.18115),
    "Secret Factory": (41.446333, -90.565487),
    "The Other Factory": (35.1175, -89.971107)
}

In [89]:
df["Factory_Lat"] = df["Factory"].map(lambda x: factory_coords[x][0])
df["Factory_Lon"] = df["Factory"].map(lambda x: factory_coords[x][1])

df[["Factory","Factory_Lat","Factory_Lon"]].head()

           Factory  Factory_Lat  Factory_Lon
0  Wicked Choccy's    32.076176   -81.088371
1  Wicked Choccy's    32.076176   -81.088371
2    Lot's O' Nuts    32.881893  -111.768036
3    Lot's O' Nuts    32.881893  -111.768036
4  Wicked Choccy's    32.076176   -81.088371

In [90]:
region_coords = {
    "Interior": (39.7392, -104.9903),   # Denver
    "Atlantic": (36.8508, -76.2859),    # East coast
    "Gulf": (29.7604, -95.3698),        # Houston
    "Pacific": (34.0522, -118.2437)     # Los Angeles
}

In [91]:
df["Customer_Lat"] = df["Region"].map(region_coords).str[0]
df["Customer_Lon"] = df["Region"].map(region_coords).str[1]

In [92]:
df[df["Customer_Lat"].isnull()]["Region"].unique()

array([], dtype=object)

In [93]:
from geopy.distance import geodesic

def calculate_distance(row):
    factory_loc = (row["Factory_Lat"], row["Factory_Lon"])
    customer_loc = (row["Customer_Lat"], row["Customer_Lon"])
    return geodesic(factory_loc, customer_loc).km

df["Distance_km"] = df.apply(calculate_distance, axis=1)

In [94]:
df["Distance_km"].describe()

count    10194.000000
mean      1805.753303
std       1114.278390
min        615.679772
25%        689.149482
50%       1387.922455
75%       3255.298419
max       3457.708101
Name: Distance_km, dtype: float64

In [95]:
df.to_csv("data/processed.csv", index=False)